import type { SelectOption } from "./types";

export const STATE_OPTIONS: SelectOption[] = [
  { value: "AL", label: "Alabama (AL)" },
  { value: "AK", label: "Alaska (AK)" },
  { value: "AZ", label: "Arizona (AZ)" },
  { value: "AR", label: "Arkansas (AR)" },
  { value: "CA", label: "California (CA)" },
  { value: "CO", label: "Colorado (CO)" },
  { value: "CT", label: "Connecticut (CT)" },
  { value: "DE", label: "Delaware (DE)" },
  { value: "FL", label: "Florida (FL)" },
  { value: "GA", label: "Georgia (GA)" },
  { value: "HI", label: "Hawaii (HI)" },
  { value: "ID", label: "Idaho (ID)" },
  { value: "IL", label: "Illinois (IL)" },
  { value: "IN", label: "Indiana (IN)" },
  { value: "IA", label: "Iowa (IA)" },
  { value: "KS", label: "Kansas (KS)" },
  { value: "KY", label: "Kentucky (KY)" },
  { value: "LA", label: "Louisiana (LA)" },
  { value: "ME", label: "Maine (ME)" },
  { value: "MD", label: "Maryland (MD)" },
  { value: "MA", label: "Massachusetts (MA)" },
  { value: "MI", label: "Michigan (MI)" },
  { value: "MN", label: "Minnesota (MN)" },
  { value: "MS", label: "Mississippi (MS)" },
  { value: "MO", label: "Missouri (MO)" },
  { value: "MT", label: "Montana (MT)" },
  { value: "NE", label: "Nebraska (NE)" },
  { value: "NV", label: "Nevada (NV)" },
  { value: "NH", label: "New Hampshire (NH)" },
  { value: "NJ", label: "New Jersey (NJ)" },
  { value: "NM", label: "New Mexico (NM)" },
  { value: "NY", label: "New York (NY)" },
  { value: "NC", label: "North Carolina (NC)" },
  { value: "ND", label: "North Dakota (ND)" },
  { value: "OH", label: "Ohio (OH)" },
  { value: "OK", label: "Oklahoma (OK)" },
  { value: "OR", label: "Oregon (OR)" },
  { value: "PA", label: "Pennsylvania (PA)" },
  { value: "RI", label: "Rhode Island (RI)" },
  { value: "SC", label: "South Carolina (SC)" },
  { value: "SD", label: "South Dakota (SD)" },
  { value: "TN", label: "Tennessee (TN)" },
  { value: "TX", label: "Texas (TX)" },
  { value: "UT", label: "Utah (UT)" },
  { value: "VT", label: "Vermont (VT)" },
  { value: "VA", label: "Virginia (VA)" },
  { value: "WA", label: "Washington (WA)" },
  { value: "WV", label: "West Virginia (WV)" },
  { value: "WI", label: "Wisconsin (WI)" },
  { value: "WY", label: "Wyoming (WY)" },
];

export const CARGO_OPTIONS: SelectOption[] = [
  { value: "crgo_genfreight", label: "General Freight" },
  { value: "crgo_household", label: "Household Goods" },
  { value: "crgo_metalsheet", label: "Metal: Sheets, Coils, Rolls" },
  { value: "crgo_motoveh", label: "Motor Vehicles" },
  { value: "crgo_drivetow", label: "Driveaway/Towaway" },
  { value: "crgo_logpole", label: "Logs, Poles, Beams, Lumber" },
  { value: "crgo_bldgmat", label: "Building Materials" },
  { value: "crgo_mobilehome", label: "Mobile Homes" },
  { value: "crgo_machlrg", label: "Machinery, Large Objects" },
  { value: "crgo_produce", label: "Fresh Produce" },
  { value: "crgo_liqgas", label: "Liquids/Gases" },
  { value: "crgo_intermodal", label: "Intermodal Containers" },
  { value: "crgo_passengers", label: "Passengers" },
  { value: "crgo_oilfield", label: "Oilfield Equipment" },
  { value: "crgo_livestock", label: "Livestock" },
  { value: "crgo_grainfeed", label: "Grain, Feed, Hay" },
  { value: "crgo_coalcoke", label: "Coal/Coke" },
  { value: "crgo_meat", label: "Meat" },
  { value: "crgo_garbage", label: "Garbage, Refuse, Trash" },
  { value: "crgo_usmail", label: "Mail" },
  { value: "crgo_chem", label: "Chemicals" },
  { value: "crgo_drybulk", label: "Commodities Dry Bulk" },
  { value: "crgo_coldfood", label: "Refrigerated Food" },
  { value: "crgo_beverages", label: "Beverages" },
  { value: "crgo_paperprod", label: "Paper Products" },
  { value: "crgo_utility", label: "Utility" },
  { value: "crgo_farmsupp", label: "Farm Supplies" },
  { value: "crgo_construct", label: "Construction" },
  { value: "crgo_waterwell", label: "Water-Well" },
  { value: "crgo_cargoothr", label: "Other" },
];

export const ALL_COLUMNS = [
  "mcs150_date", "add_date", "status_code", "dot_number", "dun_bradstreet_no", "phy_omc_region",
  "safety_inv_terr", "carrier_operation", "business_org_id", "mcs150_mileage", "mcs150_mileage_year",
  "mcs151_mileage", "total_cars", "mcs150_update_code_id", "prior_revoke_flag", "prior_revoke_dot_number",
  "phone", "fax", "cell_phone", "company_officer_1", "company_officer_2", "business_org_desc",
  "truck_units", "power_units", "bus_units", "fleetsize", "review_id", "recordable_crash_rate",
  "mail_nationality_indicator", "phy_nationality_indicator", "phy_barrio", "mail_barrio", "carship",
  "docket1prefix", "docket1", "docket2prefix", "docket2", "docket3prefix", "docket3", "pointnum",
  "total_intrastate_drivers", "mcsipstep", "mcsipdate", "hm_ind", "interstate_beyond_100_miles",
  "interstate_within_100_miles", "intrastate_beyond_100_miles", "intrastate_within_100_miles",
  "total_cdl", "total_drivers", "avg_drivers_leased_per_month", "classdef", "legal_name", "dba_name",
  "phy_street", "phy_city", "phy_country", "phy_state", "phy_zip", "phy_cnty",
  "carrier_mailing_street", "carrier_mailing_state", "carrier_mailing_city", "carrier_mailing_country",
  "carrier_mailing_zip", "carrier_mailing_cnty", "carrier_mailing_und_date", "driver_inter_total",
  "email_address", "review_type", "review_date", "safety_rating", "safety_rating_date", "undeliv_phy",
  "crgo_genfreight", "crgo_household", "crgo_metalsheet", "crgo_motoveh", "crgo_drivetow",
  "crgo_logpole", "crgo_bldgmat", "crgo_mobilehome", "crgo_machlrg", "crgo_produce", "crgo_liqgas",
  "crgo_intermodal", "crgo_passengers", "crgo_oilfield", "crgo_livestock", "crgo_grainfeed",
  "crgo_coalcoke", "crgo_meat", "crgo_garbage", "crgo_usmail", "crgo_chem", "crgo_drybulk",
  "crgo_coldfood", "crgo_beverages", "crgo_paperprod", "crgo_utility", "crgo_farmsupp",
  "crgo_construct", "crgo_waterwell", "crgo_cargoothr", "crgo_cargoothr_desc",
  "owntruck", "owntract", "owntrail", "owncoach", "ownschool_1_8", "ownschool_9_15",
  "ownschool_16", "ownbus_16", "ownvan_1_8", "ownvan_9_15", "ownlimo_1_8", "ownlimo_9_15",
  "ownlimo_16", "trmtruck", "trmtract", "trmtrail", "trmcoach", "trmschool_1_8", "trmschool_9_15",
  "trmschool_16", "trmbus_16", "trmvan_1_8", "trmvan_9_15", "trmlimo_1_8", "trmlimo_9_15",
  "trmlimo_16", "trptruck", "trptract", "trptrail", "trpcoach", "trpschool_1_8", "trpschool_9_15",
  "trpschool_16", "trpbus_16", "trpvan_1_8", "trpvan_9_15", "trplimo_1_8", "trplimo_9_15",
  "trplimo_16",
] as const;

export const DEFAULT_COLUMNS = [
  "dot_number", "legal_name", "power_units", "phy_city", "phy_state", "phy_zip",
];

export const EQUIPMENT_TYPE_MAPPING: Record<string, string> = {
  "Box or Van Enclosed Trailer": "Dry Van",
  "Intermodal Container Chassis or Trailer": "Chassis",
  "Flatbed or Platform Trailer": "Flatbed",
  "Reefer Trailer": "Reefer",
};

export const RECORDS_PER_PAGE = 1000;
export const MAX_RECORDS = 2500000;
export const UNIT_BATCH_SIZE = 250;
export const VIN_BATCH_SIZE = 50;
